on:
  - "push"
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on:  ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: Cache Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}

      - name: "Check Clippy"
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: "cargo clippy"
          
      - name: "Build Debug"
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: "cargo build"

      - name: Upload debug artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ runner.os }}
          path: target/debug/t2linux-installer

  release:
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on:  ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: Cache Registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          
      - name: "Install cargo-bundle"
        run: "cargo install cargo-bundle"

      - name: "Build macos Release Bundle"
        if: ${{ matrix.os == 'macos-latest' }}
        run: "cargo bundle --release --format osx"

      - name: "Build linux Release Bundle"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: "cargo bundle --release --format appimage"

      - name: "Release linux"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: softprops/action-gh-release@v3
        with:
          files: |
            'target/release/bundle/appimage/t2linux Installer.AppImage'

      - name: "Release macos"
        if: ${{ matrix.os == 'macos-latest' }}
        uses: softprops/action-gh-release@v3
        with:
          files: |
            'target/release/bundle/osx/t2linux Installer.app'

